(function(){
  "use strict";
  const d=window.DEFAULT_DINNER_DATA, cat=window.DINNER_CATALOG;
  if(!d || !cat) throw new Error("v1.4.1 audit requires v1.4 data + catalog");
  const DIV=Number(cat.portionDivisor||2.75);
  const byBlock=new Map((d.blocks||[]).map(b=>[b.code,b]));
  const nutr=cat.nutrition||{};
  const gramTargets={I001:300,I002:300,I003:500,I004:650,I005:650,I006:250,I007:300,I008:400,I009:350,I010:300,I012:250,I013:250,I014:350,I015:300,I016:350,I017:300,I018:250,I019:75,I020:300,I021:300,I022:225};
  const meatFishCodes=new Set([...Object.keys(gramTargets),"I011","I023"]);
  const round10=n=>Math.max(0,Math.round(Number(n||0)/10)*10),round1=n=>Math.max(0,Math.round(Number(n||0))),fmt=n=>Number.isInteger(Number(n))?String(Number(n)):String(Number(n)).replace(/\.0+$/,'');
  function targetFor(r,code,old){if(code==="I006"&&r.blocks?.P22)return 175;if(code==="I012"&&r.blocks?.P22)return 125;if(code==="I006"&&r.blocks?.P08)return 300;if(code==="I011")return Math.min(Number(old),4);if(code==="I023")return Number(old);const t=gramTargets[code];return t==null?Number(old):Math.min(Number(old),t)}
  function replaceRequirementAmount(text,code,oldQty,newQty){let s=String(text||"");if(oldQty===newQty)return s;if(code==="I011"){const re=new RegExp(`\\b${oldQty}\\s+(sausages?)\\b`,`i`);return s.replace(re,`${newQty} $1`)}if(code==="I023")return s;const oldEsc=String(oldQty).replace('.', '\\.');const re=new RegExp(`(~?\\b${oldEsc}\\s*g\\b)`,`i`);return s.replace(re,`${fmt(newQty)}g`)}
  function subtractNutrition(r,code,oldQty,newQty){if(!r.nutrition||oldQty<=newQty)return;const n=nutr[code];if(!n)return;const dq=Number(oldQty)-Number(newQty);r.nutrition.kcal=round10(Number(r.nutrition.kcal||0)-dq*Number(n.kcal||0)/DIV);r.nutrition.p=round1(Number(r.nutrition.p||0)-dq*Number(n.p||0)/DIV);r.nutrition.c=round1(Number(r.nutrition.c||0)-dq*Number(n.c||0)/DIV);r.nutrition.f=round1(Number(r.nutrition.f||0)-dq*Number(n.f||0)/DIV)}
  (d.recipes||[]).forEach(r=>{let directProteinChange=false;Object.keys(r.ingredients||{}).forEach(code=>{if(!meatFishCodes.has(code))return;const oldQty=Number(r.ingredients[code]||0),newQty=targetFor(r,code,oldQty);if(!(oldQty>0)||newQty>=oldQty)return;directProteinChange=true;r.ingredients[code]=newQty;r.requirement=replaceRequirementAmount(r.requirement,code,oldQty,newQty);subtractNutrition(r,code,oldQty,newQty)});if(!directProteinChange&&r.blocks?.P06){const oldQty=350,newQty=250;r.requirement=String(r.requirement||"").replace(/\b350\s*g\b/i,"250g");const n={kcal:1.85,p:0.27,f:0.08},dq=oldQty-newQty;if(r.nutrition){r.nutrition.kcal=round10(Number(r.nutrition.kcal||0)-dq*n.kcal/DIV);r.nutrition.p=round1(Number(r.nutrition.p||0)-dq*n.p/DIV);r.nutrition.f=round1(Number(r.nutrition.f||0)-dq*n.f/DIV)}}if(r.blocks?.P04)r.requirement=String(r.requirement||"").replace(/^4 thighs \/ 500g/i,"3–4 thighs / ~500g");if(r.blocks?.P05)r.requirement=String(r.requirement||"").replace(/^8 drumsticks \/ 650g/i,"5–6 drumsticks / ~650g");if(r.blocks?.P16)r.requirement=String(r.requirement||"").replace(/1 freezer pack \/ ~?12 Lamb kofta rolled as balls/i,"1 freezer pack / 8 small lamb meatballs").replace(/1 freezer pack \/ ~?12 kofta Lamb kofta/i,"1 freezer pack / 8 kofta").replace(/1 freezer pack \/ ~?12 Lamb kofta\/meatballs/i,"1 freezer pack / 8 kofta/meatballs").replace(/1 freezer pack \/ ~?12 Lamb kofta/i,"1 freezer pack / 8 kofta");if(r.blocks?.P22)r.requirement=String(r.requirement||"").replace(/1 freezer pack \/ ~?12 Classic beef-pork meatballs/i,"1 freezer pack / 6–8 classic beef-pork meatballs").replace(/8–10 P22 meatballs/i,"6–8 P22 meatballs");const codes=Object.keys(r.blocks||{}).filter(c=>Number(r.blocks[c]||0)>0);r.blockGuide=codes.length?codes.map(c=>`${c} · ${byBlock.get(c)?.name||"Unknown block"}`).join("; "):"No shared Sunday prep block";r.portionEquivalent=2.75});
  const blockPatch={P01:{unitMeans:"300g",batchIngredients:"900g chicken breast"},P02:{unitMeans:"~300g family pack"},P03:{unitMeans:"300g",batchIngredients:"900g boneless chicken thighs"},P04:{unitMeans:"3–4 cooked thighs / ~500g raw equivalent",batchIngredients:"~1.5kg bone-in chicken thighs; neutral oil and seasoning"},P05:{unitMeans:"~650g raw equivalent (about 5–6 drumsticks or 6–8 wings)",batchIngredients:"~1.9kg chicken drumsticks/wings; neutral oil/salt"},P06:{unitMeans:"250g cooked",batchIngredients:"1 large whole chicken or ~1.2kg thighs; light seasoning"},P07:{unitMeans:"~200g cooked (from 250g raw mince)",batchIngredients:"1kg beef mince; optional A01 onion base"},P08:{unitMeans:"4 small patties / ~300g total",batchYield:"8 small patties / 2 dinner packs",batchIngredients:"600g beef mince"},P09:{unitMeans:"300g",batchIngredients:"900g rump/sirloin or stir-fry beef"},P10:{unitMeans:"~275g cooked (from ~400g raw)",batchIngredients:"~1.6kg braising beef"},P11:{unitMeans:"300g",batchIngredients:"900g pork tenderloin or loin"},P13:{unitMeans:"~200g cooked (from 250g raw mince)",batchIngredients:"750g pork mince"},P14:{unitMeans:"4 sausages / ~220–250g",batchIngredients:"20 family sausages"},P16:{unitMeans:"~250g",batchIngredients:"750g lamb mince"},P17:{unitMeans:"~200g cooked (from 250g raw mince)",batchIngredients:"750g lamb mince"},P18:{unitMeans:"~250g cooked (from ~350g raw)",batchIngredients:"~1.05kg diced lamb"},P20:{unitMeans:"~300g / 3 thin fillets or 6–8 fish fingers",batchIngredients:"~1.5kg white fish loin/fillets"},P22:{unitMeans:"6–8 meatballs / ~300g raw mix",batchYield:"~32 meatballs / 4 dinner packs"},P24:{unitMeans:"~300g duck / 2 small breasts",batchIngredients:"~900g duck breast"}};Object.entries(blockPatch).forEach(([code,p])=>Object.assign(byBlock.get(code)||{},p));
  const missingRefs=[];(d.recipes||[]).forEach(r=>Object.keys(r.blocks||{}).forEach(c=>{if(!byBlock.has(c))missingRefs.push(`${r.id}:${c}`)}));d.meta=d.meta||{};d.meta.dataVersion="v1.4.1-block-clarity-protein-portions";d.meta.portionBasis="2 adults + 2 young children ≈ 2.75–3 adult-equivalent portions";d.meta.portionAudit="Protein portions reduced roughly 25–35% from v1.4 and re-audited for ~2.75–3 adult-equivalent family dinners; recipe nutrition adjusted for the reduced protein quantity.";d.meta.blockAudit=`${d.recipes.length} recipes audited; ${missingRefs.length} missing shared-block references.`;if(missingRefs.length)console.warn("Dinner v1.4.1 missing block refs",missingRefs);
})();